service: cake-financials-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Configuration for serverless-webpack
# Enable auto-packing of external modules
custom:
  myStage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2
  environment:
    MY_STAGE: ${self:custom.myStage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::cake-financials-user-data/*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::cake-financials-user-data"

functions:
  save_brokerage_creds:
    handler: save_brokerage_credentials.main
    environment:
      USER_DATA_PUBLIC_KEY: ${s3:cake-financials-config/USER_DATA_PUBLIC_KEY}
      USER_DATA_BUCKET: ${s3:cake-financials-config/USER_DATA_BUCKET}
    events:
      - http:
          path: brokerage/credentials
          method: post
          cors: true
          authorizer: aws_iam

  get_brokerage_creds_exists:
    handler: get_brokerage_credentials_exists.main
    environment:
      USER_DATA_BUCKET: ${s3:cake-financials-config/USER_DATA_BUCKET}
    events:
      - http:
          path: brokerage/credentials/exists
          method: get
          cors: true
          authorizer: aws_iam

  get_obf_brokerage_creds:
    handler: get_obfuscated_brokerage_credentials.main
    environment:
      USER_DATA_BUCKET: ${s3:cake-financials-config/USER_DATA_BUCKET}
    events:
      - http:
          path: brokerage/credentials/obfuscated
          method: get
          cors: true
          authorizer: aws_iam

  save_bank_info:
    handler: save_bank_info.main
    environment:
      USER_DATA_PUBLIC_KEY: ${s3:cake-financials-config/USER_DATA_PUBLIC_KEY}
      USER_DATA_BUCKET: ${s3:cake-financials-config/USER_DATA_BUCKET}
    events:
      - http:
          path: bank/account_info
          method: post
          cors: true
          authorizer: aws_iam

  get_bank_info_exists:
    handler: get_bank_info_exists.main
    environment:
      USER_DATA_BUCKET: ${s3:cake-financials-config/USER_DATA_BUCKET}
    events:
      - http:
          path: bank/account_info/exists
          method: get
          cors: true
          authorizer: aws_iam

  get_obf_bank_info:
    handler: get_obfuscated_bank_info.main
    environment:
      USER_DATA_BUCKET: ${s3:cake-financials-config/USER_DATA_BUCKET}
    events:
      - http:
          path: bank/account_info/obfuscated
          method: get
          cors: true
          authorizer: aws_iam